<!doctype html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Projet Tricount</title>
    </head>
    <body>
        <nav>
            <ul>
                <li><a href="index.php?route=users">Liste des utilisateurs</a></li>
                <li><a href="index.php?route=user-create">Création de compte</a></li>
                <li><a href="index.php?route=user-edit">Modification de compte</a></li>
                <li><a href="index.php?route=connexion">Connexion</a></li>
            </ul>
        </nav>
        <?php
        
            require "$template";
            
        ?>
    </body>
</html>